### ISSUE TITLE
Support for ECR

### ISSUE THREAD

**Issue by shobhitic** [crystal-lang-tools/sublime-crystal#46]
Currently, the `.ecr` files are being shown as Plain Text files. I couldn't find a way to syntax highlight there. I think it should be a part of official crystal sublime package.

**Comment by sardaukar** [comment]
I got it to work (kinda), but not sure how to make it into a package. Just save this

```
%YAML 1.2
---
file_extensions:
  - ecr
scope: text.html.ruby

contexts:
  main:
    - match: ''
      push: 'scope:text.html.basic'
      with_prototype:
        - match: "<%+#"
          scope: punctuation.definition.comment.ecr
          push:
            - meta_scope: comment.block.ecr
            - match: "%>"
              pop: true
        - match: "<%+(?!>)[-=]?"
          scope: punctuation.section.embedded.crystal
          push:
            - meta_scope: source.crystal.embedded.html
            - match: "-?%>"
              scope: punctuation.section.embedded.crystal
              pop: true
            - match: (#).*?(?=-?%>)
              scope: comment.line.number-sign.crystal
              captures:
                1: punctuation.definition.comment.crystal
            - include: "Crystal.sublime-syntax"
~
```

as `ECR.sublime-syntax` on your Sublime User packages folder.

**Comment by plambert** [comment]
This also works for me; it's not perfect but _way_ better than nothing.  :)

**Comment by dcalixto** [comment]
a fix for:  

> error loading syntax file packages user ecr.sublime-syntax apparent recursion within a with_prototype action: 25000 context sanity limit hit


```
%YAML 1.2
---
file_extensions:
  - ecr
scope: text.html.ruby
contexts:
  main:
    - include: ecr_tags
    - include: scope:text.html.basic

  ecr_tags:
    - match: "<%+#"
      scope: punctuation.definition.comment.ecr
      push: ecr_comment
    - match: "<%+(?!>)[-=]?"
      scope: punctuation.section.embedded.crystal
      push: ecr_crystal

  ecr_comment:
    - meta_scope: comment.block.ecr
    - match: "%>"
      scope: punctuation.definition.comment.ecr
      pop: true

  ecr_crystal:
    - meta_scope: source.crystal.embedded.html
    - match: "-?%>"
      scope: punctuation.section.embedded.crystal
      pop: true
    - match: (#).*?(?=-?%>)
      scope: comment.line.number-sign.crystal
      captures:
        1: punctuation.definition.comment.crystal
    - include: scope:source.crystal
```
